/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erp.sistema;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Walter Rosales
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root"); // Nodo raíz
    DefaultTreeModel treeModel = new DefaultTreeModel(root);
    JTree menu = new JTree(treeModel);
    
    // Agrega un TreeSelectionListener al JTree


    public Principal() {
        super("Sistema ERP pagina principal");
        
         // Establecer las dimensiones de la ventana
        this.setSize(800, 600);
        // JFrame frame = new JFrame("Menu principal");
        // Establecer la operación al cerrar la ventana
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Maximizar la ventana
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Hacer visible la ventana
        this.add(new JScrollPane(menu){
        
            
        
        }); // Agrega el árbol en un JScrollPane para desplazamiento
        this.pack();
        this.setVisible(true);  
        DefaultMutableTreeNode parentNode = new DefaultMutableTreeNode("Herramientas del sistema"); // Nodo padre
        DefaultMutableTreeNode childNode = new DefaultMutableTreeNode("Usuarios"); // Nodo hijo
        root.add(parentNode); // Agrega el nodo padre al nodo raíz
        parentNode.add(childNode); // Agrega el nodo hijo al nodo padre

        // Actualiza el modelo del árbol para reflejar los cambios
        treeModel.reload();
        initComponents();
        
        // Agrega un TreeSelectionListener al JTree
        menu.addTreeSelectionListener(new TreeSelectionListener() {
         @Override
         public void valueChanged(TreeSelectionEvent e) {
              DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) menu.getLastSelectedPathComponent();

                if (selectedNode != null) {
                 // Verifica si el nodo seleccionado es igual al nodo "Usuarios"
                 if (selectedNode.toString().equals("Usuarios")) {
                     // Haz algo cuando se haga clic en el nodo "Usuarios"
                        JOptionPane.showMessageDialog(null, "Haz clic en el nodo 'Usuarios'");
                     }
                 }
             }
        });

        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Principal");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
        
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
